import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'services/api_service.dart';
import 'services/iap_service.dart';
import 'services/auth_service.dart';
import 'screens/subscription_screen.dart';
import 'screens/login_screen.dart';
// import 'firebase_options.dart'; // GENERATED BY FLUTTER FIRE CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // NOTE: In a real app, use the file generated by 'flutterfire configure'
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  
  // MOCK INIT FOR COMPILATION only if no google-services.json
  // If user provides keys, uncomment real init.
  try {
     await Firebase.initializeApp(); 
  } catch (e) {
     print("Firebase init warning (expected if no keys): $e");
  }

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // Services setup
    final apiService = ApiService();
    // Auth Service depends on API to sync user
    final authService = AuthService(apiService);
    // IAP Service depends on API to verify purchase
    final iapService = IAPService(apiService);

    return MultiProvider(
      providers: [
        ChangeNotifierProvider.value(value: authService),
        ChangeNotifierProvider.value(value: iapService),
      ],
      child: MaterialApp(
        title: 'Subscribo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          useMaterial3: true,
        ),
        home: AuthWrapper(),
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context);
    
    if (authService.isAuthenticated) {
        return HomeScreen();
    } else {
        return LoginScreen();
    }
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context, listen: false);
    
    return Scaffold(
      appBar: AppBar(
        title: Text("Subscribo Home"),
        actions: [
          IconButton(
            icon: Icon(Icons.logout),
            onPressed: () => authService.signOut(),
          )
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text("Welcome!"),
            if (authService.user != null)
              Text("User: ${authService.user!.uid}", style: TextStyle(fontSize: 12, color: Colors.grey)),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => SubscriptionScreen()),
                );
              },
              child: Text("View Plans"),
            )
          ],
        ),
      ),
    );
  }
}
